; wiview — WiFi Sensing on the M5Stack Cardputer-Adv
; PlatformIO project configuration
; https://docs.platformio.org/en/latest/projectconf/index.html

[platformio]
;default_envs = cardputer, native

[env:cardputer]
platform = espressif32
board = m5stack_stamp_s3
framework = arduino
monitor_speed = 115200
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_build.partitions = default_8MB.csv
board_upload.flash_size = 8MB
build_flags =
    -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO
    -DBOARD_HAS_PSRAM=0
    -DARDUINO_M5STACK_CARDPUTER_ADV
lib_deps =
    m5stack/M5Cardputer @ ^1.2.0
    m5stack/M5Unified @ ^0.2.0

[env:native]
platform = native
test_framework = unity
test_ignore = test_desktop
src_filter = -<main.cpp>
